name: Auto Linter

on: 
  push:
    paths: "*.py"

jobs:
  Code:  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout/Clone the code
        uses: actions/checkout@v7
      - name: Install Linter
        run: pip install ruff
      - name: Checking linter
        run: ruff check .
